<a href="https://colab.research.google.com/github/SeionixAi/RL-B101-Sneha-Sebastian/blob/main/Seionix_Class1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PART 1 :Python Coding

1.Basic Program


In [1]:
name = input("Enter your name: ")

Enter your name: Sneha


In [2]:
age = int(input("Enter your age: "))

Enter your age: 24


In [3]:
print(f"My name is {name} and I am {age} years old.")

My name is Sneha and I am 24 years old.


2.Even or Odd

In [5]:
num = int(input("Enter a number: "))

Enter a number: 4


In [7]:
if num % 2 == 0:
    print("Even number")
else:
    print("Odd number")

Even number


3.List Operations

In [8]:
numbers = [10, 20, 30, 40, 50]

In [9]:
print("Sum:", sum(numbers))
print("Max:", max(numbers))
print("Min:", min(numbers))

Sum: 150
Max: 50
Min: 10


4.Function Example

In [12]:
def square(num):
    return num * num

print(square(5))

25


5.Loop Task

In [13]:
for i in range(1, 11):
  print(i)

1
2
3
4
5
6
7
8
9
10


# PART 2: NumPy Coding Tasks

In [15]:
import numpy as np

1.Create Arrays

In [16]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


2.Array Operations

In [17]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

In [18]:
print(a + b)
print(a * b)

[11 22 33]
[10 40 90]


3.Zeros and Ones

In [19]:
print(np.zeros((2, 3)))
print(np.ones((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


4.Mean, Max, Min

In [20]:
data = np.array([10, 20, 30, 40])

In [21]:
print("Mean:", np.mean(data))
print("Max:", np.max(data))
print("Min:", np.min(data))

Mean: 25.0
Max: 40
Min: 10


# PART 3: Pandas Coding Tasks

In [22]:
import pandas as pd

1.Create DataFrame

In [27]:
data = {"Name": ["Alice", "Bob", "Charlie"],"Age": [22, 24, 23],"Marks": [85, 90, 88]}
df = pd.DataFrame(data)
print(df)

      Name  Age  Marks
0    Alice   22     85
1      Bob   24     90
2  Charlie   23     88


2.Read CSV

In [25]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")
print(df.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0  


3.Basic Operations

In [28]:
print(df["Age"].mean())
print(df["Marks"].max())

23.0
90


4.Filtering

In [29]:
print(df[df["Marks"] > 85])

      Name  Age  Marks
1      Bob   24     90
2  Charlie   23     88
