# NUMPY

In [1]:
import numpy as np

1. Create Arrays

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


2.Array Operations

In [3]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

In [4]:
print(a + b)
print(a * b)

[11 22 33]
[10 40 90]


3.Zeros and Ones

In [5]:
print(np.zeros((2, 3)))
print(np.ones((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


4.Mean, Max, Min

In [6]:
data = np.array([10, 20, 30, 40])

In [7]:
print("Mean:", np.mean(data))
print("Max:", np.max(data))
print("Min:", np.min(data))

Mean: 25.0
Max: 40
Min: 10
